tab_spaces = 4
max_width=120
fn_call_width=64

reorder_imports = true

## re-enable when these land on stable
# group_imports="StdExternalCrate"
# indent_style = "Block"
# imports_granularity = "Module"