[package]
name = "dtype_variant_example_shared"
version.workspace = true
edition.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dtype_variant = { workspace = true }
